require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BedsController do

  # This should return the minimal set of attributes required to create a valid
  # Bed. As you add validations to Bed, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all beds as @beds" do
      bed = Bed.create! valid_attributes
      get :index
      assigns(:beds).should eq([bed])
    end
  end

  describe "GET show" do
    it "assigns the requested bed as @bed" do
      bed = Bed.create! valid_attributes
      get :show, :id => bed.id.to_s
      assigns(:bed).should eq(bed)
    end
  end

  describe "GET new" do
    it "assigns a new bed as @bed" do
      get :new
      assigns(:bed).should be_a_new(Bed)
    end
  end

  describe "GET edit" do
    it "assigns the requested bed as @bed" do
      bed = Bed.create! valid_attributes
      get :edit, :id => bed.id.to_s
      assigns(:bed).should eq(bed)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bed" do
        expect {
          post :create, :bed => valid_attributes
        }.to change(Bed, :count).by(1)
      end

      it "assigns a newly created bed as @bed" do
        post :create, :bed => valid_attributes
        assigns(:bed).should be_a(Bed)
        assigns(:bed).should be_persisted
      end

      it "redirects to the created bed" do
        post :create, :bed => valid_attributes
        response.should redirect_to(Bed.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bed as @bed" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bed.any_instance.stub(:save).and_return(false)
        post :create, :bed => {}
        assigns(:bed).should be_a_new(Bed)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bed.any_instance.stub(:save).and_return(false)
        post :create, :bed => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bed" do
        bed = Bed.create! valid_attributes
        # Assuming there are no other beds in the database, this
        # specifies that the Bed created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bed.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bed.id, :bed => {'these' => 'params'}
      end

      it "assigns the requested bed as @bed" do
        bed = Bed.create! valid_attributes
        put :update, :id => bed.id, :bed => valid_attributes
        assigns(:bed).should eq(bed)
      end

      it "redirects to the bed" do
        bed = Bed.create! valid_attributes
        put :update, :id => bed.id, :bed => valid_attributes
        response.should redirect_to(bed)
      end
    end

    describe "with invalid params" do
      it "assigns the bed as @bed" do
        bed = Bed.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bed.any_instance.stub(:save).and_return(false)
        put :update, :id => bed.id.to_s, :bed => {}
        assigns(:bed).should eq(bed)
      end

      it "re-renders the 'edit' template" do
        bed = Bed.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bed.any_instance.stub(:save).and_return(false)
        put :update, :id => bed.id.to_s, :bed => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bed" do
      bed = Bed.create! valid_attributes
      expect {
        delete :destroy, :id => bed.id.to_s
      }.to change(Bed, :count).by(-1)
    end

    it "redirects to the beds list" do
      bed = Bed.create! valid_attributes
      delete :destroy, :id => bed.id.to_s
      response.should redirect_to(beds_url)
    end
  end

end
